### ISSUE TITLE
[BUG]: auto-assign doesn't work

### ISSUE THREAD

**Issue by Falcion** [Falcion/Patternugit#170]
### What the essence of the bug

```shell
Run kentaro-m/auto-assign-action@v1.2.2
  with:
    repo-token: ***
    configuration-path: .github/auto_assign.yml
Error: Not Found
```

Can be fixed by providing this configuration (from project's README):

```yaml
name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/workflows/auto-assign.yml'
```

### Version of an project's essence

Another or unknown

### On what OS you have encountered the bug.

Not important

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

### Security policy

- [X] I agree to follow this project's security policy.
