### ISSUE TITLE
[FEATURE]: reintegrate "lint-staged" workflow into the repository

### ISSUE THREAD

**Issue by Falcion** [Falcion/Patternugit#189]
### What the essence of your feature request

Integrate workflow named "lint-staged" in the repository, this would improve code smell:
```yaml

name: Lint
on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null
permissions: { }
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: Super-linter
        uses: super-linter/super-linter@v6.7.0  # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          FILTER_REGEX_EXCLUDE: .*workflows/.*
          LINTER_RULES_PATH: /
          IGNORE_GITIGNORED_FILES: true
```

Since there is already integrated linting mechanism through hooks (HUSKY), it would be a good idea to implement it through workflows and adapt repository to "clean-and-good" code standards.

### On what OS you want to maintain your request.

Not important

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

### Security policy

- [X] I agree to follow this project's security policy.
